# TTS 论文抓取配置
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "liutaocode"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 10
publish_readme: True
publish_gitpage: False
publish_wechat: False
json_readme_path: "./tts-arxiv-daily.json"
json_gitpage_path: "./tts-arxiv-daily-web.json"
json_wechat_path: "./docs/tts-arxiv-daily-wechat.json"
md_readme_path: "README.md"
md_gitpage_path: "./docs/index.md"
md_wechat_path: "./docs/wechat.md"
keywords: {
  "TTS": {
    "filters": ["TTS", "Text to speech", "Speech Synthesis", "Voice Synthesis", "Speech Generation", "Neural Speech Synthesis", "Neural TTS"]
  }
}
update_paper_links: False